<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#strings">What are Strings?</a>
        </li>
        <li>
            <a href="#index">Indexing</a>
            <ul>
                <li><a href="neg">Negative Indexing</a></li>
                <li><a href="slice">Slicing</a></li>
                <li><a href="stride">Stride</a></li>
                <li><a href="concat">Concatenate Strings</a></li>
            </ul>
                <li>
            <a href="#dic">Dictionaries</a>
            <ul>
                <li><a href="content">What are Dictionaries?</a></li>
                <li><a href="key">Keys</a></li>
            </ul>
        </li>
                <li>
            <a href="#loop">Loops</a>
            <ul>
                <li><a href="range">Range</a></li>
                <li><a href="for">What is <code>for</code> loop?</a></li>
                <li><a href="while">What is <code>while</code> loop?</a></li>
            </ul>
        </li>
                <li>
            <a href="#func">Functions</a>
            <ul>
                <li><a href="content">What is a function?</a></li>
                <li><a href="var">Variables</a></li>
            </ul>
        </li>
        <li><a href="pre">Pre-defined functions</a>
         <ul>
         <li><a href="content">Global Variables</a></li>
            </ul>
        </li>
         <li>
            <a href="numpy">What is Numpy?</a>
            <ul>
                <li><a href="type">Type</a></li>
                <li><a href="other">Other Attributes</a></li>
            </ul>
        </li>
        <li>
            <a href="op">Numpy Array Operations</a>
            <ul>
                <li><a href="add">Array Addition</a></li>
                <li><a href="multi">Array Multiplication</a></li>
                <li><a href="prod">Product of Two Numpy Arrays</a></li>
                <li><a href="dot">Dot Product</a></li>
                <li><a href="cons">Adding Constant to a Numpy Array</a></li>
            </ul>
        </li>
            <ul>
        <li><a href="create">Create a 2D Numpy Array</a></li>
        <li><a href="access">Accessing different elements of a Numpy Array</a></li>
        <li><a href="op">Basic Operations</a></li>
    </ul>
</div>
    </ul>
</div>

<hr>

<h2 id="strings">What are Strings?</h2>

In [5]:
# Use quotation marks for defining string

"Michael Jackson"

'Michael Jackson'

In [6]:
# Digitals and spaces in string

'1 2 3 4 5 6 '

'1 2 3 4 5 6 '

In [7]:
# Special characters in string

'@#2_#]&*^%$'

'@#2_#]&*^%$'

In [8]:
# Print the string

print("hello!")

hello!


In [9]:
# Assign string to variable

Name = "Michael Jackson"
Name

'Michael Jackson'

<hr>

<h2 id="index">Indexing</h2>

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsIndex.png" width="600" align="center" />

In [11]:
# Print the first element in the string

print(Name[0])

M


In [12]:
# Print the element on index 6 in the string

print(Name[6])

l


<h3 id="neg">Negative Indexing</h3>

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsNeg.png" width="600" align="center" />

In [14]:
# Print the last element in the string

print(Name[-1])

n


In [15]:
# Find the length of string

len("Michael Jackson")

15

<h3 id="slice">Slicing</h3>

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsStride.png" width="600" align="center" />

In [17]:
# Get every second element. The elments on index 1, 3, 5 ...

Name[::2]

'McalJcsn'

In [18]:
# Get every second element in the range from index 0 to index 4

Name[0:5:2]

'Mca'

<h3 id="concat">Concatenate Strings</h3>

In [20]:
# Concatenate two strings

Statement = Name + "is the best"
Statement

'Michael Jacksonis the best'

In [21]:
# Print the string for 3 times

3 * "Michael Jackson"

'Michael JacksonMichael JacksonMichael Jackson'

In [22]:
# Concatenate strings

Name = "Michael Jackson"
Name = Name + " is the best"
Name

'Michael Jackson is the best'

<h2 id="Dic">Dictionaries</h2>

<h3 id="content">What are Dictionaries?</h3>

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsList.png" width="650" />

In [24]:
# Create the dictionary

Dict = {"key1": 1, "key2": "2", "key3": [3, 3, 3], "key4": (4, 4, 4), ('key5'): 5, (0, 1): 6}
Dict

{'key1': 1,
 'key2': '2',
 'key3': [3, 3, 3],
 'key4': (4, 4, 4),
 'key5': 5,
 (0, 1): 6}

In [25]:
# Access to the value by the key

Dict["key1"]

1

In [26]:
# Access to the value by the key

Dict[(0, 1)]

6

In [27]:
# Create a sample dictionary

release_year_dict = {"Thriller": "1982", "Back in Black": "1980", \
                    "The Dark Side of the Moon": "1973", "The Bodyguard": "1992", \
                    "Bat Out of Hell": "1977", "Their Greatest Hits (1971-1975)": "1976", \
                    "Saturday Night Fever": "1977", "Rumours": "1977"}
release_year_dict

{'Thriller': '1982',
 'Back in Black': '1980',
 'The Dark Side of the Moon': '1973',
 'The Bodyguard': '1992',
 'Bat Out of Hell': '1977',
 'Their Greatest Hits (1971-1975)': '1976',
 'Saturday Night Fever': '1977',
 'Rumours': '1977'}

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsStructure.png" width="650" />

<h3 id="key">Keys</h3>

In [28]:
# Get value by keys

release_year_dict['Thriller'] 

'1982'

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsKeyOne.png" width="500" />

In [30]:
# Get all the keys in dictionary

release_year_dict.keys() 

dict_keys(['Thriller', 'Back in Black', 'The Dark Side of the Moon', 'The Bodyguard', 'Bat Out of Hell', 'Their Greatest Hits (1971-1975)', 'Saturday Night Fever', 'Rumours'])

In [31]:
# Get all the values in dictionary

release_year_dict.values() 

dict_values(['1982', '1980', '1973', '1992', '1977', '1976', '1977', '1977'])

In [32]:
# Append value with key into dictionary

release_year_dict['Graduation'] = '2007'
release_year_dict

{'Thriller': '1982',
 'Back in Black': '1980',
 'The Dark Side of the Moon': '1973',
 'The Bodyguard': '1992',
 'Bat Out of Hell': '1977',
 'Their Greatest Hits (1971-1975)': '1976',
 'Saturday Night Fever': '1977',
 'Rumours': '1977',
 'Graduation': '2007'}

In [33]:
# Delete entries by key

del(release_year_dict['Thriller'])
del(release_year_dict['Graduation'])
release_year_dict

{'Back in Black': '1980',
 'The Dark Side of the Moon': '1973',
 'The Bodyguard': '1992',
 'Bat Out of Hell': '1977',
 'Their Greatest Hits (1971-1975)': '1976',
 'Saturday Night Fever': '1977',
 'Rumours': '1977'}

In [34]:
# Verify the key is in the dictionary

'The Bodyguard' in release_year_dict

True

<h2 id="loop">Loops</h2>

<h3 id="range">Range</h3>

In [35]:
# Use the range

range(3)

range(0, 3)

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsRange.png" width="300" />

<h3 id="for">What is <code>for</code> loop?</h3>

In [36]:
# For loop example

dates = [1982,1980,1973]
N = len(dates)

for i in range(N):
    print(dates[i])     

1982
1980
1973


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsForRange.gif" width="800" />

In [37]:
# Example of for loop

for i in range(0, 8):
    print(i)

0
1
2
3
4
5
6
7


In [38]:
# Exmaple of for loop, loop through list

for year in dates:  
    print(year)   

1982
1980
1973


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsForList.gif" width="800">

In [40]:
# Use for loop to change the elements in list

squares = ['red', 'yellow', 'green', 'purple', 'blue']

for i in range(0, 5):
    print("Before square ", i, 'is',  squares[i])
    squares[i] = 'weight'
    print("After square ", i, 'is',  squares[i])

Before square  0 is red
After square  0 is weight
Before square  1 is yellow
After square  1 is weight
Before square  2 is green
After square  2 is weight
Before square  3 is purple
After square  3 is weight
Before square  4 is blue
After square  4 is weight


In [41]:
# Loop through the list and iterate on both index and element value

squares=['red', 'yellow', 'green', 'purple', 'blue']

for i, square in enumerate(squares):
    print(i, square)

0 red
1 yellow
2 green
3 purple
4 blue


<h3 id="while">What is <code>while</code> loop?</h3>

In [42]:
# While Loop Example

dates = [1982, 1980, 1973, 2000]

i = 0
year = 0

while(year != 1973):
    year = dates[i]
    i = i + 1
    print(year)

print("It took ", i ,"repetitions to get out of loop.")

1982
1980
1973
It took  3 repetitions to get out of loop.


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsWhile.gif" width="650" />

<h2 id="func">Functions</h2>

<h3 id="content">What is a Function?</h3>

In [44]:
# First function example: Add 1 to a and store as b

def add(a):
    b = a + 1
    print(a, "if you add one", b)
    return(b)

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/FuncsDefinition.png" width="500" /> 

In [45]:
# Get a help on add function

help(add)

Help on function add in module __main__:

add(a)



In [46]:
# Call the function add()

add(1)

1 if you add one 2


2

In [47]:
# Define a function for multiple two numbers

def Mult(a, b):
    c = a * b
    return(c)

In [48]:
# Use mult() multiply two integers

Mult(2, 3)

6

In [49]:
# Use mult() multiply two floats

Mult(10.0, 3.14)

31.400000000000002

In [50]:
# Use mult() multiply two different type values together

Mult(2, "Michael Jackson ")

'Michael Jackson Michael Jackson '

<h3 id="var">Variables</h3>

In [51]:
# Function Definition

def square(a):
    
    # Local variable b
    b = 1
    c = a * a + b
    print(a, "if you square + 1", c) 
    return(c)


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/FuncsVar.png" width="500" />

In [52]:
# Initializes Global variable  

x = 3
# Makes function call and return function a y
y = square(x)
y

3 if you square + 1 10


10

If there is no <code>return</code> statement, the function returns <code>None</code>. The following two functions are equivalent:

In [54]:
# Define functions, one with return value None and other without return value

def MJ():
    print('Michael Jackson')
    
def MJ1():
    print('Michael Jackson')
    return(None)

In [55]:
# See the output

MJ()

Michael Jackson


In [56]:
# See the output

MJ1()

Michael Jackson


In [57]:
# Define the function for combining strings

def con(a, b):
    return(a + b)


In [58]:
# Test on the con() function

con("This ", "is")

'This is'

<h2 id="pre">Pre-defined functions</h2>

In [59]:
# Build-in function print()

album_ratings = [10.0, 8.5, 9.5, 7.0, 7.0, 9.5, 9.0, 9.5] 
print(album_ratings)

[10.0, 8.5, 9.5, 7.0, 7.0, 9.5, 9.0, 9.5]


In [60]:
# Use sum() to add every element in a list or tuple together

sum(album_ratings)


70.0

In [61]:
# Show the length of the list or tuple

len(album_ratings)

8

<h2 id="global">Global variables</h2>

In [63]:
# Example of global variable

artist = "Michael Jackson"
def printer1(artist):
    internal_var = artist
    print(artist, "is an artist")
    
printer1(artist)

Michael Jackson is an artist


In [64]:
artist = "Michael Jackson"

def printer(artist):
    global internal_var 
    internal_var= "Whitney Houston"
    print(artist,"is an artist")

printer(artist) 
printer(internal_var)

Michael Jackson is an artist
Whitney Houston is an artist


In [65]:
# Import the libraries

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

<h2 id="numpy">What is Numpy?</h2>

In [66]:
# import numpy library

import numpy as np 

In [67]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a


array([0, 1, 2, 3, 4])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumOneNp.png" width="500" />

In [68]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


<h3 id="type">Type</h3>

In [69]:
# Check the type of the array

type(a)

numpy.ndarray

In [70]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int32')

In [71]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [72]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [73]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

<h3 id="other">Other Attributes</h3>

In [74]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [75]:
# Get the size of numpy array

a.size

5

In [76]:
# Get the number of dimensions of numpy array

a.ndim

1

In [77]:
# Get the shape/size of numpy array

a.shape

(5,)

In [78]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [79]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [80]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [81]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [82]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [83]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

-1

<h2 id="op">Numpy Array Operations</h2>

<h3 id="add">Array Addition</h3>

In [84]:
u = np.array([1, 0])
u

array([1, 0])

In [85]:
v = np.array([0, 1])
v

array([0, 1])

In [86]:
# Numpy Array Addition

z = u + v
z

array([1, 1])

<h3 id="multi">Array Multiplication</h3>

In [87]:
# Create a numpy array

y = np.array([1, 2])
y

array([1, 2])

In [88]:
# Numpy Array Multiplication

z = 2 * y
z


array([2, 4])

<h3 id="prod">Product of Two Numpy Arrays</h3>

In [89]:
# Create a numpy array

u = np.array([1, 2])
u

array([1, 2])

In [90]:
# Create a numpy array

v = np.array([3, 2])
v

array([3, 2])

In [91]:
# Calculate the production of two numpy arrays

z = u * v
z

array([3, 4])

<h3 id="dot">Dot Product</h3>

In [92]:
# Calculate the dot product

np.dot(u, v)

7

<h3 id="cons">Adding Constant to a Numpy Array</h3>

In [93]:

# Create a constant to numpy array

u = np.array([1, 2, 3, -1]) 
u

array([ 1,  2,  3, -1])

In [94]:
# Add the constant to array

u + 1

array([2, 3, 4, 0])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumOneAdd.gif" width="500" />

In [95]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

<h2 id="access">Create a 2D Numpy Array</h2>

In [96]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [97]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [98]:
# Show the numpy array dimensions

A.ndim

2

In [99]:

# Show the numpy array shape

A.shape

(3, 3)

In [100]:
# Show the numpy array size

A.size

9

<h2 id="access">Accessing different elements of a Numpy Array</h2>

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoEg.png" width="500" />

In [102]:
# Access the element on the second row and third column

A[1, 2]

23

In [103]:
# Access the element on the second row and third column

A[1][2]

23

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFF.png" width="400" />

In [106]:
# Access the element on the first row and first column

A[0][0]

11

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFSF.png" width="400" />

In [108]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [109]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoTST.png" width="400" />

<h2 id="op">Basic Operations</h2>

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoAdd.png" width="500" />

In [111]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [112]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [113]:
# Add X and Y

Z = X + Y
Z


array([[3, 1],
       [1, 3]])


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoDb.png" width="500" />

In [114]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [115]:
# Multiply Y with 2

Z = 2 * Y
Z


array([[4, 2],
       [2, 4]])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoMul.png" width="500" />


In [116]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y


array([[2, 1],
       [1, 2]])

In [117]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X


array([[1, 0],
       [0, 1]])

In [118]:

# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [119]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A


array([[0, 1, 1],
       [1, 0, 1]])

In [120]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B


array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [121]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [122]:

# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [123]:

# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [124]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])